routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   return redirect('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


	// UserManagement Routes
	// ======== Athuntication ========== //
	// UserManagement Module Require To Access this group Routes
	Route::group([ 'namespace' => 'UserManagement', 'prefix' => 'UserManagement'], function () {

	    Route::get('/', 'UserManagementController@index')->name('usermanagement.index');
		// User CRUD Routes
		Route::resource('users', 'UserController');
        Route::get('change-password','UserController@ChangePassword')->name('password.change');
        Route::post('change-password','UserController@UpdatePassword')->name('password.update');
        Route::put('users/status/{id}', 'UserController@toggleStatus')->name('users.toggleStatus');


        // // User Groups CRUD Routes
        Route::resource('usergroups', 'UserGroupController');
        Route::put('usergroups/status/{id}', 'UserGroupController@toggleStatus')->name('usergroups.toggleStatus');
        // Route::resource('groups', 'UserGroupController')->middleware('module:UserManagement');



	});
Route::resource('events', 'EventManagement\EventController');
// Route::resource('marquees', 'MarqueeManagement\MarqueeController');
// Route::put('marquees/status/{id}', 'MarqueeManagement\MarqueeController@toggleStatus')->name('marquees.toggleStatus');
// Route::resource('services', 'MarqueeManagement\ServiceController');
// Route::get('Services/addService/{id}', 'MarqueeManagement\ServiceController@addservice')->name('addservice');
// Route::resource('gallerys', 'MarqueeManagement\ImageUploadController');
// Route::get('gallerys/addimage/{id}', 'MarqueeManagement\ImageUploadController@addimage')->name('addimage');
// Route::POST('gallerys/storeimage', 'MarqueeManagement\ImageUploadController@storeimage')->name('storeimage');

// Route::post('deleteimage','MarqueeManagement\ImageUploadController@fileDestroy')->name('deleteimage');

// Route::post('image/upload/store','MarqueeManagement\ImageUploadControllerr@fileStore');

app/UserGroup.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UserGroup extends Model
{
    public function users()
    {
        return $this->hasMany("App\User", "user_group_id", "id");
    }

    public function submodules()
    {
        return $this->belongsToMany("App\SubModule", "groupHasModules", "user_group_id", "module_id");
    }

    protected $fillable = ["name", "description"];

    protected $casts = ["status" => "boolean"];
}

app/Http/Controllers/UserManagement/UserGroupController.php
<?php

namespace App\Http\Controllers\UserManagement;

use App\UserGroup;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Str;
use Toastr;

class UserGroupController extends Controller
{

    public function index(){

        $usergroups = UserGroup::all();
        return view("usergroup.index", compact('usergroups'));

    }

    public function show($slug){

        $usergroup = UserGroup::where('slug', $slug)->firstorFail();
        return view("usergroup.show", compact('usergroup'));

    }
    public function create(){
        $usergroups = new UserGroup();
        return view('usergroup.create')->with('usergroup',$usergroups);
    }


    public function store(Request $request){
        $this->validate($request,[
            'name' => 'string|required|unique:user_groups',
            'description' =>'string|nullable'
        ]);
        $usergroup = new UserGroup;
        $usergroup->name = $request->name;
        $usergroup->description = $request->description;
        $usergroup->slug = Str::slug($request->name,'-');

        $usergroup->save();
        Toastr::success('User Group added Successfully', 'Success', ["positionClass" => "toast-bottom-right"]);

        return redirect()->back();
    }
    public function edit($slug)
    {
        $usergroup =  UserGroup::where('slug',$slug)->first();
        return view('usergroup.create')->with('usergroup',$usergroup);
    }
    public function update(Request $request, $slug)
    {
        $this->validate($request,[
            'name' => 'string|required',
            'description' =>'string|nullable'
        ]);
        $usergroups = UserGroup::where('slug',$slug)->first();

        $usergroups->name = $request->name;
        $usergroups->description = $request->description;
         $usergroups->save();
        Toastr::success('User Group updated Successfully', 'Success', ["positionClass" => "toast-bottom-right"]);

        return redirect()->route('usergroups.index');
    }

    public function toggleStatus($id)
    {
        $usergroup = UserGroup::find($id);
        if($usergroup->status){
            $usergroup->status = 0;
        } else {
            $usergroup->status = 1;
        }
        $usergroup->save();
        return redirect()->back();
    }
}

resources/views/usergroup/partials/form.blade.php
@extends('layouts.block')

@section('b-title')
    <h2> <i class="fa fa-users"></i> <strong> Create User Group </strong> </h2>
@endsection


@section('b-options')
    <a href="javascript:void(0)" class="btn btn-alt btn-sm btn-default" data-toggle="tooltip" title="" data-original-title="Create User"><i class="fa fa-plus"></i></a>
@overwrite

@section('b-content')
    <form method="POST" class="form-horizontal form-bordered" action="{{ ($usergroup->slug) ? route('usergroups.update', $usergroup->slug ) : route('usergroups.store') }}">

        @csrf
        @if($usergroup->slug)
            @method('PUT')
        @else
            @method('POST')
        @endif

        <div class="form-group @error('name') has-error @enderror @if(session('danger')) has-error @endif">
            <label class="col-md-3 control-label" for="name">Name <span class="text-danger">*</span></label>
            <div class="col-md-9">
                <input type="text" id="name" name="name" class="form-control" value="{{ old('name', $usergroup->name) }}" placeholder="User Group Name" required autofocus>
                @error('name')
                <span class="help-block animation-slideDown text-danger">{{ $message }}</span>
                @enderror
                @if(session('danger'))
                    <span class="help-block animation-slideDown text-danger">{{session('danger')}}</span>
                @endif
            </div>
        </div>
        <div class="form-group @error('description') has-error @enderror">
            <label class="col-md-3 control-label" for="description">Description</label>
            <div class="col-md-9">
                <textarea id="description" name="description" rows="9" class="form-control" placeholder="User Group Description">{{ old('name', $usergroup->description) }}</textarea>
                @error('description')
                <span class="help-block animation-slideDown text-danger">{{ $message }}</span>
                @enderror
            </div>
        </div>

        <div class="form-group form-actions">
            <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-paper-plane"></i> Submit</button>
                <button type="reset" class="btn btn-sm btn-warning"><i class="fa fa-repeat"></i> Reset</button>
            </div>
        </div>
    </form>
@endsection

resources/views/usergroup/partials/list.blade.php
@extends('layouts.block' , [ 'b_type' => 'table', "b_options" => 'ft'])

@section('b-title')
    <h2> <i class="fa fa-users"></i> <strong> User Groups </strong></h2>
@overwrite
@section('b-subtitle')
    List
@overwrite

@section('b-options')
    <a href="{{ route('usergroups.create') }}" class="btn btn-alt btn-sm btn-default" data-toggle="tooltip" title="" data-original-title="Create User"><i class="fa fa-plus"></i></a>
@overwrite

@section('b-thead')
    <tr>
        <th class="text-center">ID</th>
        <th>Name</th>
        <th>Description</th>
        <th class="text-center">Status</th>
        <th class="text-center">Actions</th>
    </tr>
@endsection

@section('b-tbody')
    @foreach ($usergroups as $row)
        <tr>
            <td class="text-center">
                {{ $row->id }}
            </td>
            <td>
                {{ $row->name }}
            </td>
            <td>
                {{ $row->description }}
            </td>
            <td class="text-center">
                <form action="{{ route('usergroups.toggleStatus', $row->id) }}" method="post">
                    @csrf
                    @method('PUT')
                    <label class="switch switch-info">
                        <input {{ $row->status ? 'checked' : '' }} onclick="this.form.submit()" type="checkbox">
                        <span {{ $row->status ? 'title=Active' : 'title=Inactive' }} data-toggle="tooltip"></span>
                    </label>
                </form>
            </td>
            <td class="text-center">
                <div class="btn-group">
                    <a href="{{ route('usergroups.show', $row->slug) }}" data-toggle="tooltip" title="View" class="btn btn-xs btn-info"><i class="fa fa-eye"></i></a>
                    <a href="{{ route('usergroups.edit',$row->slug) }}" data-toggle="tooltip" title="Edit" class="btn btn-xs btn-primary"><i class="fa fa-pencil"></i></a>

                </div>
            </td>
        </tr>
    @endforeach

@endsection