routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   return redirect('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


	// UserManagement Routes
	// ======== Athuntication ========== //
	// UserManagement Module Require To Access this group Routes
	Route::group([ 'namespace' => 'UserManagement', 'prefix' => 'UserManagement'], function () {

	    Route::get('/', 'UserManagementController@index')->name('usermanagement.index');
		// User CRUD Routes
		Route::resource('users', 'UserController');
        Route::get('change-password','UserController@ChangePassword')->name('password.change');
        Route::post('change-password','UserController@UpdatePassword')->name('password.update');
        Route::put('users/status/{id}', 'UserController@toggleStatus')->name('users.toggleStatus');


        // // User Groups CRUD Routes
        Route::resource('usergroups', 'UserGroupController');
        Route::put('usergroups/status/{id}', 'UserGroupController@toggleStatus')->name('usergroups.toggleStatus');
        // Route::resource('groups', 'UserGroupController')->middleware('module:UserManagement');



	});
Route::resource('events', 'EventManagement\EventController');
// Route::resource('marquees', 'MarqueeManagement\MarqueeController');
// Route::put('marquees/status/{id}', 'MarqueeManagement\MarqueeController@toggleStatus')->name('marquees.toggleStatus');
// Route::resource('services', 'MarqueeManagement\ServiceController');
// Route::get('Services/addService/{id}', 'MarqueeManagement\ServiceController@addservice')->name('addservice');
// Route::resource('gallerys', 'MarqueeManagement\ImageUploadController');
// Route::get('gallerys/addimage/{id}', 'MarqueeManagement\ImageUploadController@addimage')->name('addimage');
// Route::POST('gallerys/storeimage', 'MarqueeManagement\ImageUploadController@storeimage')->name('storeimage');

// Route::post('deleteimage','MarqueeManagement\ImageUploadController@fileDestroy')->name('deleteimage');

// Route::post('image/upload/store','MarqueeManagement\ImageUploadControllerr@fileStore');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    public function usergroup()
    {
        return $this->belongsTo("App\UserGroup", "user_group_id", "id");
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'contact', 'user_group_id', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'status' => 'boolean'
    ];
}

app/Http/Controllers/UserManagement/UserController.php
<?php

namespace App\Http\Controllers\UserManagement;

use App\User;
use App\UserGroup;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\Http\Controllers\Controller;
use Illuminate\Support\Str;
use Toastr;

class UserController extends Controller
{

    public function index()
    {
    	$users = User::all();
    	return view("user.index", compact('users'));

    }

    public function store( Request $request){

        $this->validate($request,[
            "name" => "string|required",
            "email" => "email|required|unique:users",
            'password' => 'required|string|min:6',
            "contact" => 'required|max:12|string|nullable',
            "user_group_id" => 'integer|required',


        ]);

        $user = new User;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = $request->password;
        $user->contact = $request->contact;
        $user->user_group_id = $request->user_group_id;
        $user->slug = Str::slug($request->name,'-');

        $user->save();
        Toastr::success('User added Successfully', 'Success', ["positionClass" => "toast-bottom-right"]);

        return redirect()->route('users.index');

    }


    public function create(){
        $users = new User();
        return view('user.create')->with('user',$users)->with('usergroups',UserGroup::all());
    }

    public function show($slug){

        $user = User::where('slug', $slug)->firstorFail();
        return view("user.show", compact('user'));
    }

    public function toggleStatus($id)
    {
        $user = User::find($id);
        if($user->status){
            $user->status = 0;
        } else {
            $user->status = 1;
        }
        $user->save();
        return redirect()->back();
    }

    public function ChangePassword()
    {
        return view('user.password_change');
    }

    public function UpdatePassword(Request $request)
    {
        $data = $request->validate([
            'current_password' => ['required'],
            'new_password' => ['required', 'min:8'],
            'new_confirm_password' => ['required', 'same:new_password'],
        ]);

        if (Hash::check($data['current_password'], auth()->user()->password)){
            User::find(auth()->user()->id)->update(['password'=> Hash::make($data['new_password'])]);
            Toastr::success('Password Changed Successfully', 'Success', ["positionClass" => "toast-bottom-right"]);
        }else{
            $request->session()->flash('danger', 'Current Password Incorrect');
        }
        return redirect()->back();

    }

}

resources/views/user/partials/form.blade.php
@extends('layouts.block')

@section('b-title')
    <h2> <i class="fa fa-user"></i> <strong> Create User  </strong> </h2>
@endsection



@section('b-content')
    <form method="POST" class="form-horizontal form-bordered" action="{{route('users.store') }}" autocomplete="off">
        @csrf

        <div class="form-group @error('name') has-error @enderror @if(session('danger')) has-error @endif">
            <label class="col-md-3 control-label" for="name">Name <span class="text-danger">*</span></label>
            <div class="col-md-9">
                <input type="text" id="name" name="name" class="form-control" value="{{ old('name', $user->name) }}"                                placeholder="User Name" required autofocus>
                @error('name')
                <span class="help-block animation-slideDown text-danger">{{ $message }}</span>
                @enderror
                @if(session('danger'))
                    <span class="help-block animation-slideDown text-danger">{{session('danger')}}</span>
                @endif
            </div>
        </div>
        <div class="form-group @error('description') has-error @enderror">
            <label class="col-md-3 control-label" for="email">Email <span class="text-danger">*</span></label>
            <div class="col-md-9">
                <input type="email" id="email" name="email" class="form-control" value="{{ old('email', $user->email) }}"                                placeholder="User Email" required >
                @error('email')
                <span class="help-block animation-slideDown text-danger">{{ $message }}</span>
                @enderror
            </div>
        </div>
        <div class="form-group @error('password') has-error @enderror">
            <label class="col-md-3 control-label" for="password">Password <span class="text-danger">*</span></label>
            <div class="col-md-9">
                <input type="password" id="password" name="password" class="form-control" value="" placeholder="User Password" required >
                @error('password')
                <span class="help-block animation-slideDown text-danger">{{ $message }}</span>
                @enderror
            </div>
        </div>

        <div class="form-group @error('contact') has-error @enderror">
            <label class="col-md-3 control-label" for="contact">Contact</label>
            <div class="col-md-9">
                <input type="number" id="contact" name="contact" class="form-control" value="{{ old('contact', $user->contact) }}"                  placeholder="User Contact"  >
                @error('contact')
                <span class="help-block animation-slideDown text-danger">{{ $message }}</span>
                @enderror
            </div>
        </div>

        <div class="form-group @error('user_group_id') has-error @enderror">
            <label class="col-md-3 control-label" for="user_group_id">User Group <span class="text-danger">*</span></label>
            <div class="col-md-9">
                <select id="user_group_id" name="user_group_id" class="form-control" size="1" required>
                    <option value="0">Please select</option>
                    @foreach( $usergroups as $usergroup)
                        <option value="{{ $usergroup->id }}">{{ $usergroup->name }}</option>
                    @endforeach

                </select>

                @error('user_group_id')
                <span class="help-block animation-slideDown text-danger">{{ $message }}</span>
                @enderror
            </div>
        </div>

        <div class="form-group form-actions">
            <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-paper-plane"></i> Submit</button>
                <button type="reset" class="btn btn-sm btn-warning"><i class="fa fa-repeat"></i> Reset</button>
            </div>
        </div>
    </form>
@endsection

resources/views/user/partials/info.blade.php
@extends('layouts.block', ["b_options" => 'ft'])

@section('b-title')
   <h2> <i class="fa fa-file-o"></i> <strong>{{ $user->name }}</strong> Info</h2>
@overwrite

@section('b-content')
    @parent
    <table class="table table-borderless table-striped">
        <tbody>
        <tr>
            <td style="width: 20%;"><strong>Email</strong></td>
            <td>{{ $user->email  }}</td>
        </tr>
        <tr>
            <td><strong>Contact</strong></td>
            <td> {{ $user->contact ?? "Null" }} </td>
        </tr>
        <tr>
            <td><strong>User Group</strong></td>
            <td><a href="{{ route("usergroups.show", $user->usergroup->slug)  }}"> {{ $user->usergroup->name  }} </a></td>
        </tr>
        <tr>
            <td><strong>Registered Date</strong></td>
            <td> {{ $user->created_at  }} </td>
        </tr>
        <tr>
            <td><strong>Last Update</strong></td>
            <td> {{ $user->updated_at  }} </td>
        </tr>
        <tr>
            <td><strong>Status</strong></td>
            <td>
                @if($user->status)
                    <span class="label label-success"><i class="fa fa-check"></i> Active</span>
                    @else
                    <span class="label label-danger"><i class="fa fa-times"></i> Inactive</span>
                @endif
            </td>
        </tr>
        </tbody>
    </table>

@overwrite

resources/views/user/partials/list.blade.php
@extends('layouts.block', [ 'b_type' => 'table', "b_options" => 'ft'])

@section('b-title')
    <h2> <i class="fa fa-users"></i> <strong> Users </strong> List</h2>
@overwrite

@section('b-options')
    <a href="{{ route('users.create') }}" class="btn btn-alt btn-sm btn-default" data-toggle="tooltip" title="" data-original-title="Create User"><i class="fa fa-plus"></i></a>
@overwrite

@section('b-thead')
    <tr>
        <th class="text-center">ID</th>
        <th>Name</th>
        <th>Email</th>
        <th>Group</th>
        <th class="text-center">Status</th>
        <th class="text-center">Actions</th>
    </tr>
@endsection

@section('b-tbody')
    @parent
    @foreach ($users as $row)
        @if($row->id != auth()->user()->id)
            <tr>
                <td class="text-center">
                    {{ $row->id }}
                </td>
                <td>
                    {{ $row->name }}
                </td>
                <td>
                    {{ $row->email }}
                </td>
                <td>
                {{ $row->usergroup->name }}
                </td>
                <td class="text-center">
                    <form action="{{ route('users.toggleStatus', $row->id) }}" method="post">
                        @csrf
                        @method('PUT')
                        <label class="switch switch-sm switch-info">
                            <input {{ $row->status ? 'checked' : '' }} onclick="this.form.submit()" type="checkbox">
                            <span {{ $row->status ? 'title=Inactive it' : 'title=Activate it' }} data-toggle="tooltip"></span>
                        </label>
                    </form>
                </td>
                <td class="text-center">
                    <div class="btn-group">
                        <a href="{{ route('users.show', $row->slug) }}" data-toggle="tooltip" title="View" class="btn btn-xs btn-info"><i class="fa fa-eye"></i></a>
                        <a href="javascript:void(0)" data-toggle="tooltip" title="Edit" class="btn btn-xs btn-primary"><i class="fa fa-pencil"></i></a>
                        <a href="javascript:void(0)" data-toggle="tooltip" title="Delete" class="btn btn-xs btn-danger"><i class="fa fa-times"></i></a>
                    </div>
                </td>
            </tr>
        @endif
    @endforeach

@overwrite

resources/views/user/partials/menu.blade.php
@extends('layouts.block', [ "b_options" => ''])

@section('b-title')
    <h2> <i class="fa fa-th"></i> <strong> Over View </strong> </h2>
@overwrite

@section('b-content')
    @parent
    <ul class="nav nav-pills nav-stacked"  data-toggle="tabs">
        <li class="active">
            <a href="#users">
{{--                <span class="badge pull-right">5</span>--}}
                <i class="fa fa-info-circle fa-fw"></i> <strong>Info</strong>
            </a>
        </li>
    </ul>

@overwrite

resources/views/user/partials/password_form.blade.php
@extends('layouts.block')

@section('b-title')
<h2> <i class="fa fa-asterisk"></i> <strong> Change Password </strong> </h2>
@endsection
    @section('b-content')
        <form method="POST" class="form-horizontal form-bordered" action="{{ route('password.update') }}">
            @csrf
                <div class="form-group @error('current_password') has-error @enderror @if(session('danger')) has-error @endif">
                    <label class="col-md-3 control-label" for="current_password">Current Password <span class="text-danger">*</span></label>
                    <div class="col-md-9">
                        <input type="password" id="current_password" name="current_password" class="form-control" placeholder="Current Password" required autofocus>
                        @error('current_password')
                        <span class="help-block animation-slideDown text-danger">{{ $message }}</span>
                        @enderror
                        @if(session('danger'))
                            <span class="help-block animation-slideDown text-danger">{{session('danger')}}</span>
                        @endif
                    </div>
                </div>
                <div class="form-group @error('new_password') has-error @enderror">
                    <label class="col-md-3 control-label" for="new_password">New Password <span class="text-danger">*</span> </label>
                    <div class="col-md-9">
                        <input type="password" id="new_password" name="new_password" class="form-control" placeholder="New Password" required>
                        @error('new_password')
                        <span class="help-block animation-slideDown text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group @error('new_confirm_password') has-error @enderror">
                    <label class="col-md-3 control-label" for="new_confirm_password">Confirm Password <span class="text-danger">*</span></label>
                    <div class="col-md-9">
                        <input type="password" id="new_confirm_password" name="new_confirm_password" class="form-control" placeholder="Confirm New Password" required>
                        @error('new_confirm_password')
                        <span class="help-block animation-slideDown text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group form-actions">
                    <div class="col-md-9 col-md-offset-3">
                        <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-asterisk"></i> Change Password</button>
                        <button type="reset" class="btn btn-sm btn-warning"><i class="fa fa-repeat"></i> Reset</button>
                    </div>
                </div>
            </form>
@endsection